
# Site settings
title: inu.io
baseurl: "/"
author:
  name: Hallaj
  email: hallajs@gmail.com
url: "https://inu.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-analytics
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-sitemap

# default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# sass
sass:
  sass_dir: _sass
  style: compressed

# jekyll-analytics
jekyll_analytics:
  GoogleAnalytics:
    id: UA-347447-4
    anonymizeIp: false

# pagination
paginate: 3
paginate_path: "/page/:num/"

# theme related
social:
  linkedin: hallajs
  github: hallaj
  bitbucket: hallaj

# comments
comment:
  disqus: inuio

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
