name: Github actions for deploying hallajs.net's static page

on:
  pull_request:
  push:
    branches: [master]

jobs:
  hugo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: hallaj/hallaj.github.io
          submodules: true

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: content

      - run: sed -i 's;^baseURL = .*;baseURL = "http://ghpages-stage.hallajs.net";' config.toml
        if: github.ref != 'refs/heads/master'

      - uses: peaceiris/actions-hugo@v2

      - run: hugo --minify

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: ghpages-stage.hallajs.net
        if: github.ref != 'refs/heads/master'

      - uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: hallaj/hallaj.github.io
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./public
          cname: www.hallajs.net
        if: github.ref == 'refs/heads/master'
